version: '3.9'
networks:
  backend:
    name: backend
services:
  db:
    container_name: 'db_office_material'
    image: mysql:5.7.31
    volumes:
      - ./init.sql:/data/application/init.sql
    command: --binlog_do_db=employees --expire_logs_days=10 --max_binlog_size=100M --binlog_format=row --log-bin=/var/log/mysql/mysql-bin.log --server-id=1 --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp --init-file /data/application/init.sql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks:
      - backend

#  backend:
#    container_name: "backend_office_material"
#    build: ./backend/
#    command: npm start
#    ports:
#      - "8080:8080"
#    networks:
#      - backend
#    depends_on:
#      - db
